# the selection of datapoints and the name of the corresponding metric
eetsdbMapping:
    258506 : "memory.free"
    258507 : "disk.free"
    258508 : "communication.errors"
    268580 : "state"
    350073 : "state"
    268177 : "temperature"
    268223 : "temperature"
    268224 : "humidity"
    271760 : "wind.speed"
    271761 : "rainfall"
    271762 : "visibility"
    271766 : "pressure"
    271992 : "index"
    268234 : "state"
    268237 : "state"
    268238 : "temperature"
    342898 : "state"
    342899 : "temperature"
    343296 : "state"
    343297 : "temperature"
    268218 : "temperature"
    268219 : "CO2"
    268220 : "humidity"
    268221 : "pressure"
    268222 : "noise.level"
    268267 : "noise.level"
    268359 : "light"
    268360 : "appliance"
    268361 : "appliance"
    268362 : "appliance"
    268363 : "appliance"
    268364 : "appliance"
    268365 : "power.consumption"
    268366 : "power.consumption"
    268367 : "power.consumption"
    268368 : "power.consumption"
    268369 : "power.consumption"
    268370 : "power.consumption"
    325388 : "light"
    325389 : "power.consumption"
    348904 : "light"
    271741 : "appliance"
    271742 : "power.consumption"
    271747 : "movement"
    271748 : "temperature"
    271749 : "luminosity"
    271773 : "state"
    273229 : "state"
    349023 : "appliance"
    349024 : "power.consumption"
    345835 : "power.consumption"
    349001 : "gas.consumption"

#When working with time series it is actually recommended to rather submit data as the integral (i.e. a monotinically increasing counter].
#OpenTSDB can then "differentiate" this using the rate function.
eedbintegration:
    258506 : !!python/tuple [False,0,0]
    258507 : !!python/tuple [False,0,0]
    258508 : !!python/tuple [True,1,1] # communication errors
    268580 : !!python/tuple [False,0,0]
    350073 : !!python/tuple [False,0,0]
    268177 : !!python/tuple [False,0,0]
    268223 : !!python/tuple [False,0,0]
    268224 : !!python/tuple [False,0,0]
    271760 : !!python/tuple [False,0,0]
    271761 : !!python/tuple [False,0,0]
    271762 : !!python/tuple [False,0,0]
    271766 : !!python/tuple [False,0,0]
    271992 : !!python/tuple [False,0,0]
    268234 : !!python/tuple [False,0,0]
    268237 : !!python/tuple [False,0,0]
    268238 : !!python/tuple [False,0,0]
    342898 : !!python/tuple [False,0,0]
    342899 : !!python/tuple [False,0,0]
    343296 : !!python/tuple [False,0,0]
    343297 : !!python/tuple [False,0,0]
    268218 : !!python/tuple [False,0,0]
    268219 : !!python/tuple [False,0,0]
    268220 : !!python/tuple [False,0,0]
    268221 : !!python/tuple [False,0,0]
    268222 : !!python/tuple [False,0,0]
    268267 : !!python/tuple [False,0,0]
    268359 : !!python/tuple [False,0,0]
    268360 : !!python/tuple [False,0,0]
    268361 : !!python/tuple [False,0,0]
    268362 : !!python/tuple [False,0,0]
    268363 : !!python/tuple [False,0,0]
    268364 : !!python/tuple [False,0,0]
    268365 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    268366 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    268367 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    268368 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    268369 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    268370 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    325388 : !!python/tuple [False,0,0]
    325389 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    348904 : !!python/tuple [False,0,0]
    271741 : !!python/tuple [False,0,0]
    271742 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    271747 : !!python/tuple [False,0,0]
    271748 : !!python/tuple [False,0,0]
    271749 : !!python/tuple [False,0,0]
    271773 : !!python/tuple [False,0,0]
    273229 : !!python/tuple [False,0,0]
    349023 : !!python/tuple [False,0,0]
    349024 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    345835 : !!python/tuple [True,null,3600000.] #(watt*s -> kWh)
    349001 : !!python/tuple [True,900,3600.]     #(m3 -> /h*s -> m3)

# non-numeirc eedomus values and their translation
eetsdbvalues:
        "off": 0
        "desactivee": 0
        "ok": 0
        "ferme": 0
        "aucun mouvement": 0
        "non joignable": 0
        "--": 0
        "intimite": 0
        "on": 1
        "activee": 1
        "alarme": 1
        "ouvert": 1
        "detection mouvement": 1
        "mouvement": 1
        "joignable": 1
        "normal": 1
        "alerte": 2
        "vibration": 2

# recipes to be used to correct some readings.
eetsdbrecipes:
        349001 : "fix_gazreading"
        343297 : "fix_indoorTemperature"
        342899 : "fix_indoorTemperature"

